---
deployment:
  tasks:
    - export DEPLOYPATH=/home/math2367/public_html/sistemanovo/
    - /usr/local/cpanel/3rdparty/bin/git --git-dir=/home/math2367/repositories/mondial-turismo-erp/.git --work-tree=/home/math2367/repositories/mondial-turismo-erp checkout main -f
    - /bin/cp -r /home/math2367/repositories/mondial-turismo-erp/dist/public/. $DEPLOYPATH

